services:
  inventory:
    container_name: inventory-service
    build:
      context: ./InventoryService/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  order:
    container_name: order-service
    build:
      context: ./OrderService/
      dockerfile: Dockerfile
    ports:
      - "8002:8002"