spring:
  application:
    name: OrderService
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:order
    username: sa
    password: password
    driverClassName: org.h2.Driver


server:
  port: 8002


app:
  inventory-service:
    url: http://inventory:8001/api/v1/inventory




