spring:
  profiles:
    active: dev



resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 5
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2s
    instances:
      itemStockService:
        base-config: default
      inventoryPlaceOrderService:
        base-config: default
